### ISSUE TITLE
Typos in base pcb picture

### ISSUE THREAD

**Issue by Zedliser** [kuznetckiy/pioneer-doc-en#3]
Fixes:

- Capitalise "transmit"
- "swith on" fix typo or better change to something like "boot" or "boot sequence"
- "Scrypt" -> "Script"

Pic is clickable.
[![Pic link](https://github.com/kuznetckiy/pioneer-doc-en/blob/master/_static/images/first_switch_on_2.png?raw=true)](https://github.com/kuznetckiy/pioneer-doc-en/blob/master/_static/images/first_switch_on_2.png)

**Comment by kuznetckiy** [comment]
done
